language: node_js
node_js:
  - node

jobs:
  include:
    - stage: tests
      name: sauce labs tests
      script: npm run test:sauce
      before_install:
        - if [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" != false ]; then SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY_NOT_MASTER SAUCE_USERNAME=$SAUCE_USERNAME_NOT_MASTER; fi
    - name: types
      script: npm run dtslint

before_script:
  - npm install
addons:
  sauce_connect: true
